<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Carbon;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Str;

class SurveyQuestionsSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        // Ensure User ID 8 exists (created by UserSeeder)
        $userId = 8;

        // Check if the survey already exists to prevent duplication on multiple seed runs
        $existingSurvey = DB::table('surveys')->where('slug', 'calculadora-huella-hidrica')->first();

        if ($existingSurvey) {
            // Optionally, you could delete existing questions and re-add them,
            // or skip if you want to preserve existing data.
            // For this case, let's assume if the survey exists, we don't need to re-seed it.
            // Or, more robustly, update it. For simplicity, we'll skip if it exists.
            // If you want to update, you'd fetch $surveyId = $existingSurvey->id;
            // and then conditionally update questions or delete and re-insert.
            // For now, we'll just return if it exists to avoid issues.
            // echo "Survey 'Calculadora Huella Hidrica' already exists. Skipping seeding.\n";
            // return;
            // Alternative: Delete existing questions for this survey before re-adding
            DB::table('survey_questions')->where('survey_id', $existingSurvey->id)->delete();
            $surveyId = $existingSurvey->id;
            // Update existing survey details if necessary
            DB::table('surveys')->where('id', $surveyId)->update([
                'user_id' => $userId,
                'image' => "images/PjX55AMIoeFC08Um.jpeg", // Assuming this image exists or is optional
                'title' => "Calculadora Huella Hidrica",
                'status' => "1",
                'description' => "Calculadora Huella Hidrica, se realizan preguntas a productores de vino para recolectar informacion.",
                'expire_date' => Carbon::parse('2030-12-31'), // Use a fixed, far future date
                'updated_at' => Carbon::now(),
            ]);
        } else {
            $surveyId = DB::table('surveys')->insertGetId([
                // 'id' => 700, // Remove hardcoded ID
                'user_id' => $userId,
                'image' => "images/PjX55AMIoeFC08Um.jpeg", // Assuming this image exists or is optional
                'title' => "Calculadora Huella Hidrica",
                'slug' => "calculadora-huella-hidrica", // Slug will be auto-generated by model if not provided here
                'status' => "1", // Active
                'description' => "Calculadora Huella Hidrica, se realizan preguntas a productores de vino para recolectar informacion.",
                'created_at' =>  Carbon::now(),
                'updated_at' => Carbon::now(),
                'expire_date' => Carbon::parse('2030-12-31'), // Use a fixed, far future date
            ]);
        }


        $surveyQuestionsData = [
            [
                'type' => "text",
                'question' => "Nombre",
                'description' => "Ingrese su nombre completo.",
                'data' => json_encode([]), // Corrected data field
                'survey_id' => $surveyId,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'type' => "text",
                'question' => "¿Qué tipo de fruta o frutas utiliza para la producción de vino?",
                'description' => null,
                'data' => json_encode([]),
                'survey_id' => $surveyId,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'type' => "radio", // Changed to radio for example
                'question' => "¿Usted cultiva la fruta con la que elabora el vino?",
                'description' => "Seleccione una opción.",
                'data' => json_encode(['options' => ['Sí', 'No', 'Parcialmente']]),
                'survey_id' => $surveyId,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'type' => "int", // Changed to int
                'question' => "¿Cuántos litros de vino produce mensualmente?",
                'description' => "Ingrese un valor numérico.",
                'data' => json_encode([]),
                'survey_id' => $surveyId,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'type' => "checkbox", // Changed to checkbox for example
                'question' => "¿Qué sustancias utiliza para la fermentación alcohólica del vino? (Marque todas las que apliquen)",
                'description' => null,
                'data' => json_encode(['options' => ['Levaduras seleccionadas', 'Levaduras indígenas', 'Sulfitos', 'Azúcar', 'Otro']]),
                'survey_id' => $surveyId,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'type' => "int", // Changed to int
                'question' => "¿Cuántos litros de agua consume mensualmente para la producción de vino?",
                'description' => "Ingrese un valor numérico.",
                'data' => json_encode([]),
                'survey_id' => $surveyId,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'type' => "select", // Changed to select for example
                'question' => "¿Dónde realiza la descarga de agua residual de la producción de vino?",
                'description' => "Seleccione una opción.",
                'data' => json_encode(['options' => ['Alcantarillado público', 'Pozo séptico', 'Cuerpo de agua superficial', 'Reutilización en riego', 'Otro']]),
                'survey_id' => $surveyId,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'type' => "textarea", // Changed to textarea
                'question' => "Si su respuesta fue Otro en la pregunta anterior, especificar a continuación:",
                'description' => null,
                'data' => json_encode([]),
                'survey_id' => $surveyId,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'type' => "radio", // Changed to radio
                'question' => "¿Reutiliza el agua que se genera durante la producción del vino?",
                'description' => "Seleccione una opción.",
                'data' => json_encode(['options' => ['Sí, totalmente', 'Sí, parcialmente', 'No']]),
                'survey_id' => $surveyId,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'type' => "textarea", // Changed to textarea
                'question' => "Si su respuesta fue sí en la pregunta anterior, especificar en qué reutiliza el agua:",
                'description' => null,
                'data' => json_encode([]),
                'survey_id' => $surveyId,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'type' => "text",
                'question' => "¿Qué sustancias utiliza para la desinfección de las herramientas y equipos que utiliza para la producción de vino?",
                'description' => null,
                'data' => json_encode([]),
                'survey_id' => $surveyId,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'type' => "int", // Changed to int
                'question' => "¿Usted hace cuántos años produce vino?",
                'description' => "La respuesta solo acepta valores numericos",
                'data' => json_encode([]),
                'survey_id' => $surveyId,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            // Adding a footprint type question for testing
            [
                'type' => "footprint",
                'question' => "Valore de 1 a 5 el impacto ambiental de su proceso productivo (Huella Hídrica)",
                'description' => "1 = Muy Bajo, 5 = Muy Alto",
                'data' => json_encode(['options' => ['1', '2', '3', '4', '5']]),
                'survey_id' => $surveyId,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ]
        ];

        DB::table('survey_questions')->insert($surveyQuestionsData);
    }
}
